import re
from typing import List

from langchain_classic.retrievers import MultiQueryRetriever
from qdrant_client.models import Filter, FieldCondition, Range

from config import llm, cohere_client
from prompts import multi_query_prompt, router_prompt, PROMPT_MAP
from experience import get_experience_chunk, extract_min_years


class SavedMultiQueryRetriever(MultiQueryRetriever):
    """
    Creates a new class that inherits everything from MultiQueryRetriever,
    and saves the queries generated in the last call to a variable for later display
    """
    # Store the queries generated by the LLM
    generated_queries: List[str] = []

    # Call the original function and save the generated queries
    def generate_queries(self, question: str, run_manager=None):
        queries = super().generate_queries(question, run_manager=run_manager)
        self.generated_queries = queries
        return queries


def build_retriever(vectorstore):
    """
    Create base retriever that will be used inside the MultiQueryRetriever, 
    and retrieve the top 10 relevant chunks for each generated query
    """

    # For each query → get top 10 chunks
    base_retriever = vectorstore.as_retriever(
        search_type="similarity",
        search_kwargs={"k": 10}
    )

    # Generate multi-query
    multi_query_retriever = SavedMultiQueryRetriever.from_llm(
        retriever=base_retriever,
        llm=llm,
        prompt=multi_query_prompt
    )

    return multi_query_retriever


def bm25_search(query, bm25_index, chunks, k=10):
    """Search chunks using BM25 keyword matching and return top k results."""

    tokenized_query = query.lower().split()
    # Score all chunks using keyword matching
    scores = bm25_index.get_scores(tokenized_query)
    # Pick top 10 keyword-matching chunks
    top_k_indices = sorted(range(len(scores)), key=lambda i: scores[i], reverse=True)[:k]

    return [chunks[i] for i in top_k_indices]


def merge_results(semantic_docs, bm25_docs):
    """Merge semantic and BM25 results, removing duplicates by content."""

    seen = set() # to store unique text content we've already added
    merged = []

    for doc in semantic_docs + bm25_docs:

        # check if this chunk text was already added before
        if doc.page_content not in seen:
            seen.add(doc.page_content)
            merged.append(doc)

    return merged


def rerank(query, docs, top_n=10):
    """Rerank merged docs using Cohere reranker and return top_n results."""

    response = cohere_client.rerank(
        model="rerank-english-v3.0",
        query=query,
        documents=[doc.page_content for doc in docs],
        top_n=top_n,
    )

    # Return indices of the best documents (in order)
    return [docs[r.index] for r in response.results]



def build_experience_answer(retrieved_docs: list, min_years: float, chunks: list) -> str:
    """
    Build the answer for experience queries directly from metadata,
    appending each candidate's experience section chunk below their summary line.
    """

    # If no candidates were retrieved
    if not retrieved_docs:
        return "No suitable candidates were found based on the provided criteria."

    blocks = []

    for i, doc in enumerate(retrieved_docs, 1):
        name  = doc.metadata.get("candidate_name", "Unknown")
        years = doc.metadata.get("years_of_experience", "N/A")

        # Find the experience section chunk for this candidate
        experience_section = get_experience_chunk(name, chunks)

        block = f"{i}. {name} - {years} years of experience"
        if experience_section:
            block += f"\n\n{experience_section}"

        blocks.append(block)

    return "\n\n---\n\n".join(blocks)


def run_rag(query, multi_query_retriever, bm25_index, chunks):
    """
    Run the full RAG pipeline:
      1. Detect if the query requires a years-of-experience filter
      2. Semantic retrieval via MultiQueryRetriever (Qdrant)
      3. BM25 keyword retrieval
      4. Merge and deduplicate results
      5a. Experience queries: deduplicate to one chunk per candidate,
          build answer directly from metadata — no LLM call
      5b. All other queries: rerank with Cohere, build context, call LLM
    """

    try:
        # Extract minimum years of experience required from the query (if any)
        min_years = extract_min_years(query)

        # Apply Qdrant filter for experience if detected (for semantic seach)
        if min_years is not None:

            multi_query_retriever.retriever.search_kwargs["filter"] = Filter(
                must=[
                    FieldCondition(
                        key="years_of_experience",
                        range=Range(gte=min_years)
                    )
                ]
            )

        # Remove filter if query is not experience-related
        else:
            multi_query_retriever.retriever.search_kwargs.pop("filter", None)

        # Semantic retrieval using MultiQueryRetriever (vector search)
        semantic_docs = multi_query_retriever.invoke(query)
        query_list = multi_query_retriever.generated_queries

        # Keyword retrieval
        bm25_docs = bm25_search(query, bm25_index, chunks, k=10)

        # Filter by experience if detected (for keyword seach)
        if min_years is not None:
            bm25_docs = [
                d for d in bm25_docs
                if d.metadata.get("years_of_experience", 0) >= min_years
            ]

        # Merge semantic + BM25 results and remove duplicates
        merged_docs = merge_results(semantic_docs, bm25_docs)

        # EXPERIENCE QUERY — no LLM --> answer straight from metadata
        if min_years is not None:

            # Keep one chunk per candidate (the first one seen after merging)
            seen_candidates = set()
            retrieved_docs = []

            for doc in merged_docs:
                candidate = doc.metadata.get("candidate_name", "")

                if candidate not in seen_candidates:
                    seen_candidates.add(candidate)
                    retrieved_docs.append(doc)

            # Build the answer directly based on the experience section
            response = build_experience_answer(retrieved_docs, min_years, chunks)

            return response, retrieved_docs, query_list, {}, {}

        # Rerank the returned chunks
        retrieved_docs = rerank(query, merged_docs, top_n=10)

        # Group chunks by candidate
        candidate_groups = {}

        for doc in retrieved_docs:
            candidate = doc.metadata.get("candidate_name", "")

            # create list if candidate not seen before
            if candidate not in candidate_groups:
                candidate_groups[candidate] = []

            # add this chunk to the candidate
            candidate_groups[candidate].append(doc.page_content.strip())

        # Build years_map (name → years of experience)
        years_map = {}

        for doc in retrieved_docs:
            name = doc.metadata.get("candidate_name", "")

            if name and name not in years_map:
                yoe = doc.metadata.get("years_of_experience")
                if yoe is not None:
                    years_map[name] = yoe

        # Filter out low-experience candidates for senior queries
        senior_keywords = ["senior", "lead", "principal", "head of"]
        is_senior_query = any(kw in query.lower() for kw in senior_keywords)

        if is_senior_query:
            candidate_groups = {
                name: texts
                for name, texts in candidate_groups.items()
                if years_map.get(name, 0) >= 3
            }

        # Build structured context (one block per candidate)
        blocks = []

        for i, (candidate, texts) in enumerate(candidate_groups.items(), 1):
            combined_text = "\n\n".join(texts)  # combine all chunks of this candidate

            # Get years from the first doc of this candidate
            years = years_map.get(candidate, "unknown")

            block = f"=== CANDIDATE {i}: {candidate} (Years of Experience: {years}) ===\n{combined_text}"
            blocks.append(block)

        context_text = "\n\n".join(blocks)
    
        # Route query to the right prompt
        router_response = llm.invoke(
            router_prompt.format_messages(query=query)
        ).content.strip().upper()

        print(f"🔀 Query type detected: {router_response}") # Print query type

        # Fallback to GENERAL if unrecognized
        selected_prompt = PROMPT_MAP.get(router_response, PROMPT_MAP["GENERAL"])

        # Format prompt with query + retrieved context
        formatted_prompt = selected_prompt.format_messages(
            query=query,
            context=context_text
        )

        response = llm.invoke(formatted_prompt).content.strip()

        return response, retrieved_docs, query_list, candidate_groups, years_map

    except Exception as e:
        error_message = str(e)

        if "jailbreak" in error_message or "content_filter" in error_message:
            response = (
                "⚠️ Your message was flagged as a potential prompt injection attempt "
                "and could not be processed. Please ask a valid question about the uploaded CVs."
            )
        else:
            response = error_message

        return response, [], [], {}, {}